services:
  db:
    image: postgres:17-alpine
    container_name: ptb-fastapi-db
    volumes:
      - ptb-fastapi-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    restart: always
  bot:
    build: .
    container_name: ptb-fastapi-bot
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - .:/code
    depends_on:
      - db
    restart: always

volumes:
  ptb-fastapi-db: